2023-05-17 11:29:16.924880: ("process_node_form() missing 1 required positional argument: 'selections'",)process_node_form() missing 1 required positional argument: 'selections' corpbodies_filtered
2023-05-17 11:32:53.312706: ('can only concatenate str (not "NoneType") to str',)can only concatenate str (not "NoneType") to str corpbodies_filtered
2023-05-18 05:06:31.729365: ('can only concatenate str (not "NoneType") to str',)can only concatenate str (not "NoneType") to str collections_filtered
2023-05-18 05:18:14.133298: ('can only concatenate str (not "NoneType") to str',)can only concatenate str (not "NoneType") to str collections_filtered
2023-05-18 09:25:33.491395: ("process_node_form() missing 1 required positional argument: 'selections'",)process_node_form() missing 1 required positional argument: 'selections' oralhistories_filtered
Internal Server Error: /discover/people/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ed/PycharmProjects/wikidataDiscovery/discover/views.py", line 23, in people
    from . import forms
  File "/home/ed/PycharmProjects/wikidataDiscovery/discover/forms.py", line 43, in <module>
    class BackButtonForm(forms.Form):
  File "/home/ed/PycharmProjects/wikidataDiscovery/discover/forms.py", line 44, in BackButtonForm
    back_value = forms.CharField(required=True, max_length=1, value=1)
  File "/usr/local/lib/python3.10/dist-packages/django/forms/fields.py", line 267, in __init__
    super().__init__(**kwargs)
TypeError: Field.__init__() got an unexpected keyword argument 'value'
"GET /discover/people/ HTTP/1.1" 500 94807
2023-05-18 11:14:31.623805: ('can only concatenate str (not "NoneType") to str',)can only concatenate str (not "NoneType") to str people_filtered
Internal Server Error: /discover/people_filtered/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ed/PycharmProjects/wikidataDiscovery/discover/views.py", line 47, in people_filtered
    bbf = forms.BackButtonForm(curr_request.POST)
TypeError: BackButtonForm.__init__() takes 1 positional argument but 2 were given
"POST /discover/people_filtered/ HTTP/1.1" 500 77065
2023-05-18 11:58:33.342119: ('can only concatenate str (not "NoneType") to str',)can only concatenate str (not "NoneType") to str people_filtered
2023-05-18 12:00:17.848661: ('can only concatenate str (not "NoneType") to str',)can only concatenate str (not "NoneType") to str people_filtered
Internal Server Error: /discover/collections_filtered/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ed/PycharmProjects/wikidataDiscovery/discover/views.py", line 240, in collections_filtered
    obj = queue.get_request(0)
  File "/home/ed/PycharmProjects/wikidataDiscovery/discover/queue.py", line 13, in get_request
    obj = queue.pop(key)  # get entire queue entry
IndexError: pop from empty list
"POST /discover/collections_filtered/ HTTP/1.1" 500 81107
Internal Server Error: /discover/orals_filtered/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ed/PycharmProjects/wikidataDiscovery/discover/views.py", line 344, in oralhistories_filtered
    obj = queue.get_request(0)
  File "/home/ed/PycharmProjects/wikidataDiscovery/discover/queue.py", line 13, in get_request
    obj = queue.pop(key)  # get entire queue entry
IndexError: pop from empty list
"POST /discover/orals_filtered/ HTTP/1.1" 500 81430
